Expanding CRD definition, adding OpenAPIv3 schema
3scale/k8sapp-initiative pull request #18
Opened 2020-11-20 12:05 UTC by damianpm

Closes https://github.com/3scale/k8sapp-initiative/issues/17
It expands our CRD with a OpenAPIv3 schema for products
Also, expands our products properties to match current 3scale products

2020-11-23 08:41 UTC, didierofrivia requested changes
most important would be the timestamp for updated and created at

2020-11-23 08:41 UTC, didierofrivia commented on products_examples.yml
> +  updated_at: "September 22, 2020 10:23"
This would need to be a timestamp

2020-11-23 08:41 UTC, didierofrivia commented on products_examples.yml
> +
don't forget to add a new line at the end of file ;)

2020-11-23 08:41 UTC, didierofrivia commented on product_crd.yml
> +                  links:
good to have them, not super necessary for the POC tho

2020-11-23 08:41 UTC, didierofrivia commented on product_crd.yml
> +                  links:
question: are you running a OAS3 validator?

2020-11-23 09:52 UTC, damianpm commented on product_crd.yml
> +                  links:
I'm not running any validator, but when you run `kubectl apply` it validates the schema
<img width="661" alt="Screenshot 2020-11-23 at 10 51 09" src="https://user-images.githubusercontent.com/13486237/99948505-dbfcc280-2d79-11eb-8dcd-c42689614bf2.png">

2020-11-24 09:30 UTC, didierofrivia approved these changes

2020-11-27 07:47 UTC, merged